version: "3.9"
services:
  server:
    build: .
    command: python view.py
    env_file:
      - .env
    ports:
    - "5000:5000"
    volumes:
      - .:/python-flask
  web:
    build: ./client
    ports:
      - "3000:3000"
    volumes:
      - ./client:/user/src/app
    depends_on:
      - server